### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by MartinMa-SH** [keke1023/Padavan#6]
你好，帮忙看看是什么问题，谢谢！
![image](https://user-images.githubusercontent.com/66724349/132449765-f8300b0d-d2e6-4bb8-810b-b9bbf6a81187.png)

**Comment by keke1023** [comment]
源码里的htop早就更新到3.0.5了并且目录下就有现成的包不需要再次下载

**Comment by MartinMa-SH** [comment]
哦，我的错误。请问Padavan左上角的Logo怎么能修改回去？

**Comment by kkjoy** [comment]
3.0.5的htop 貌似运行起来会卡死，具体原因不清楚，所以还是回退3.0.2吧
