### ISSUE TITLE
CPU负载90%以上

### ISSUE THREAD

**Issue by MartinMa-SH** [keke1023/Padavan#8]
使用科学上网时，CPU负载有时候会达到90%以上，整个网络会全部被卡死；如果关闭科学上网，CPU负载就不会出现90%以上的情况，什么情况？

**Comment by MartinMa-SH** [comment]
我有重新云编译了v2ray(版本v4.34.0)，不会再出现CPU过载的问题了。
另外问一下，我云编译的v2ray有17M多，你的版本怎么只有3-5M呢，精简版？

**Comment by keke1023** [comment]
我用的是xray core的upx压缩的二进制文件
